### ISSUE TITLE
Use case gathering and structuring

### ISSUE THREAD

**Issue by rdeltour** [w3c/dpub-pwp-ucr#1]
This issue is a first attempt to describe what we have and what's missing, to better identify the work areas.
## Use cases on the wiki
- [ ] Styling and Layout: see issue #3
- [ ] Domain-Specific Content Types: see issue #4
- [ ] Identifiers: see issue #5
- [ ] Metadata: see issue #6
- [ ] Content & Markup: see issue #7
- [ ] Interaction: see issue #8
- [ ] Accessibility and Personalization: see issue #9
- [ ] Internationalization: see issue #10
- [ ] Social Reading and Annotations: see issue #11
- [ ] Packaging and Distribution: see issue #12
- [ ] Publishing Workflow Effectiveness: see issue #13
- [ ] DRM: see issue #14
- [ ] Security: see issue #16
- [ ] Pagination/DOM interaction: see issue #15
## Other sources

See also:
- EPUB 3.1's [Browser Friendly Format (BFF) Use Cases & Requirements
  ](https://docs.google.com/document/d/1ZTBiSyyIgQMXh_9Ubtep4I7TfW6Yu6l8e06-9EKaNQU/edit?ts=564ccc1a&pref=2&pli=1#heading=h.v0la5426mf86)
- [CSV on the Web: UC&R](https://www.w3.org/TR/csvw-ucr/). In our [11 jan 2016 meeting](https://www.w3.org/2016/01/11-dpub-minutes.html) Markus hinted at using the  doc as a good example.

**Comment by hlflanagan** [comment]
I believe we've managed to address the organization in the first public working draft.
